name: Laravel CI - Unit Tests

on:
  push:
    branches: ["**"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare SQLite
        run: |
          touch database/database.sqlite
          cp .env.example .env
          php artisan key:generate

      - name: Configure SQLite env
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/pest --colors=always --coverage=none
